#!/bin/sh

echo "HOST=$HOST" >> .env
echo "PORT=$PORT" >> .env
echo "DATABASE_HOST=$DATABASE_HOST" >> .env
echo "DATABASE_PORT=$DATABASE_PORT" >> .env
echo "DATABASE_NAME=$DATABASE_NAME" >> .env
echo "DATABASE_USERNAME=$DATABASE_USERNAME" >> .env
echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
echo "DATABASE_SSL=$DATABASE_SSL" >> .env
echo "ACCESS_KEY_ID=$ACCESS_KEY_ID" >> .env
echo "ACCESS_SECRET=$ACCESS_SECRET" >> .env
echo "REGION_NAME=$REGION_NAME" >> .env
echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> .env