#!/bin/sh

echo "HOST=$HOST" >> .env
echo "PORT=$PORT" >> .env
echo "DATABASE_HOST=$DATABASE_HOST" >> .env
echo "DATABASE_PORT=$DATABASE_PORT" >> .env
echo "DATABASE_NAME=$DATABASE_NAME" >> .env
echo "DATABASE_USERNAME=$DATABASE_USERNAME" >> .env
echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
echo "DATABASE_SSL=$DATABASE_SSL" >> .env
echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
echo "AWS_ACCESS_SECRET=$AWS_ACCESS_SECRET" >> .env
echo "AWS_REGION_NAME=$AWS_REGION_NAME" >> .env
echo "AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME" >> .env